services:
  adder:
    build:
      context: .
      dockerfile: docker/lambda.Dockerfile
      args:
        LAMBDA_NAME: adder
    image: adder-lambda
    command: ["adder.main.handler"]
    ports:
      - "9001:8080"
    networks:
      - lambda-network

  multiplier:
    build:
      context: .
      dockerfile: docker/lambda.Dockerfile
      args:
        LAMBDA_NAME: multiplier
    image: multiplier-lambda
    command: ["multiplier.main.handler"]
    ports:
      - "9002:8080"
    networks:
      - lambda-network

networks:
  lambda-network:
    name: lambda-network
